## Category of the shop settings
Shop:
  gui:
    ## Prefix of the gui, if you are in the data gui,
    ## it will appear like that in the title of the GUI : <dataGuiPrefix> <this>
    buy:
    sell:
    allsell:
    
    ## Option for the data GUI, this GUI is useful for choosing the exact number of items you want to sell or buy
    data:
      ## Prefix of the gui, it will appear like that in the title of the GUI: <this> <buy/sell prefix>
      prefix:
      items:
        ## Line of Lore added on an item shop,
        ## it was added to the item so that the player can know the sale price or the purchase price
        ### Use : !sell! to get the sell price.
        ### Use : !buy! to get the buy price.
        lore:
        ## ItemStack, on click it open the GUI to choice if you want more of 1 stack
        #### Use ItemWritter to transform your itemstack in text
        moreItems:
        ## ItemStack, on click it open the GUI to validate you choice
        validate:
    validate:
      ## Prefix of the gui, it will appear like that in the title of the GUI: <this> <buy/sell/allSell prefix>
      prefix:
      ## Name of the green glass item
      accept:
      ## Name of the red glass item
      deny:
  ## Message dedicated to the shop category
  message:
    ## Message that was appears when people sell something
    ### Use : !gain! to get the gain
    ### Use : !content! to get the sold items name.
    ### Use : !size! to get the size of the sold item.
    sell:
    ## Message that was appears when people buy something
    ### Use : !price! to get the price
    ### Use : !content! to get the sold items name.
    ### Use : !size! to get the size of the sold item.
    buy:
    ## Message that was appears when people sell all something
    ### Use : !gain! to get the gain
    ### Use : !content! to get the sold items name.
    allsell:
    error:
      ## Message that was appears when people does not have enough money
      noMoney:
      ## Message that was appears when people does not have enough itemStack in his inventory
      noItem:
      ## Message that was appears when people does not have any specifics ItemStack in his inventory
      hasItem: